language: go

go:
  - 1.7
  - 1.8
  - tip

install:
  - go get -t -v ./...

script:
  - diff -u <(echo -n) <(gofmt -d .)
  - go vet $(go list ./... | grep -v /vendor/)
  - go test -v -race -tags=integration

matrix:
  allow_failures:
    - go: tip
